import { TEvents } from "./types";

export const data: TEvents[] = [
  {
    id: 1,
    title: "Музыкальный фестиваль «ЛетоЗвук»",
    description: "Открытый фестиваль под открытым небом с участием локальных и зарубежных групп.",
    categories: ["Музыка", "Фестиваль", "На свежем воздухе"],
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Парк Горького, Москва",
    date: "2025-06-22T18:00:00",
  },
  {
    id: 2,
    title: "Выставка современного искусства",
    description: "Сотни произведений от молодых и признанных художников России.",
    categories: ["Искусство", "Выставка"],
    image: "https://images.unsplash.com/photo-1628642881538-b80bfc5209de?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Центральный выставочный зал «Манеж», Санкт-Петербург",
    date: "2025-06-10T12:00:00",
  },
  {
    id: 3,
    title: "Театральная постановка «Гамлет»",
    description: "Классика Шекспира в современной интерпретации от театра «Современник».",
    categories: ["Театр", "Культура"],
    image: "https://images.unsplash.com/photo-1553782749-5ab8693a5f4f?q=80&w=1978&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Театр «Современник», Москва",
    date: "2025-06-15T19:30:00",
  },
  {
    id: 4,
    title: "Открытый мастер-класс по акварели",
    description: "Научитесь основам акварельной живописи в парке.",
    categories: ["Творчество", "Мастер-класс", "На свежем воздухе"],
    image: "https://images.unsplash.com/photo-1533158388470-9a56699990c6?q=80&w=1955&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Парк Сокольники, Москва",
    date: "2025-07-01T14:00:00",
  },
  {
    id: 5,
    title: "Ночь кино",
    description: "Показ трёх фильмов подряд на большом экране под звездами.",
    categories: ["Кино", "На свежем воздухе"],
    image: "https://images.unsplash.com/photo-1664231323172-711277f096d5?q=80&w=2150&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Кинотеатр под открытым небом, Казань",
    date: "2025-06-29T21:00:00",
  },
  {
    id: 6,
    title: "Фестиваль еды и напитков",
    description: "Попробуйте кухни народов мира, лекции от шефов и мастер-классы.",
    categories: ["Еда", "Фестиваль", "Семейное"],
    image: "https://images.unsplash.com/photo-1678646142794-253fdd20fa05?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "ВДНХ, Москва",
    date: "2025-06-20T13:00:00",
  },
  {
    id: 7,
    title: "Благотворительный марафон",
    description: "Забег в поддержку фонда помощи детям. Все средства идут на благотворительность.",
    categories: ["Спорт", "Благотворительность", "Семейное"],
    image: "https://images.unsplash.com/photo-1719299246416-b4c069be9caf?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Набережная реки Казанки, Казань",
    date: "2025-06-16T09:00:00",
  },
  {
    id: 8,
    title: "Лекция: Искусственный интеллект и будущее",
    description: "Обсуждаем, как ИИ изменит работу, обучение и нашу жизнь.",
    categories: ["Наука", "Образование", "Технологии"],
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Технопарк Сколково, Москва",
    date: "2025-06-25T18:00:00",
  },
  {
    id: 9,
    title: "Концерт симфонической музыки",
    description: "Выступление государственного симфонического оркестра под открытым небом.",
    categories: ["Музыка", "Классика"],
    image: "https://images.unsplash.com/photo-1551696785-927d4ac2d35b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    location: "Площадь Искусств, Санкт-Петербург",
    date: "2025-07-03T20:00:00",
  },
  {
    id: 10,
    title: "Фестиваль настольных игр",
    description: "Для всех возрастов: от UNO до Dungeons & Dragons.",
    categories: ["Игры", "Семейное", "Творчество"],
    image: "/images/events/boardgames.jpg",
    location: "Гик-пространство «Dice & Beans», Новосибирск",
    date: "2025-06-30T11:00:00",
  },

  // Добавим еще 10 похожих
  {
    id: 11,
    title: "Показ мод молодых дизайнеров",
    description: "Талантливые дизайнеры представляют свои коллекции на летнем подиуме.",
    categories: ["Мода", "Культура"],
    image: "/images/events/fashion-show.jpg",
    location: "Арт-кластер «Флакон», Москва",
    date: "2025-07-05T17:00:00",
  },
  {
    id: 12,
    title: "Турнир по шахматам",
    description: "Прими участие или поболей за лучших шахматистов города.",
    categories: ["Игры", "Спорт", "Образование"],
    image: "/images/events/chess.jpg",
    location: "Шахматный клуб, Екатеринбург",
    date: "2025-07-07T10:00:00",
  },
  {
    id: 13,
    title: "Open mic: стендап вечер",
    description: "Вечер открытого микрофона — посмейся вместе с нами!",
    categories: ["Юмор", "Развлечения", "Культура"],
    image: "/images/events/standup.jpg",
    location: "Кафе «Смешинка», Москва",
    date: "2025-07-01T20:00:00",
  },
  {
    id: 14,
    title: "Детский праздник с анимацией",
    description: "Прыжки на батуте, аниматоры, конкурсы и подарки.",
    categories: ["Дети", "Семейное"],
    image: "/images/events/kids-party.jpg",
    location: "Центральный парк, Тверь",
    date: "2025-06-18T12:00:00",
  },
  {
    id: 15,
    title: "Ярмарка хендмейда",
    description: "Уникальные изделия ручной работы от мастеров по всей стране.",
    categories: ["Творчество", "Ярмарка"],
    image: "/images/events/handmade.jpg",
    location: "Лофт-площадка «Ткачи», Санкт-Петербург",
    date: "2025-07-09T11:00:00",
  },
  {
    id: 16,
    title: "Летний лекторий по экологии",
    description: "Цикл лекций на тему устойчивого развития и зелёных технологий.",
    categories: ["Образование", "Экология", "Наука"],
    image: "/images/events/ecology.jpg",
    location: "Экоцентр «Заповедники», Москва",
    date: "2025-06-26T16:00:00",
  },
  {
    id: 17,
    title: "Караоке-баттл",
    description: "Соревнуемся за звание лучшего голоса вечера!",
    categories: ["Развлечения", "Музыка"],
    image: "/images/events/karaoke.jpg",
    location: "Клуб «Voice», Краснодар",
    date: "2025-06-19T21:00:00",
  },
  {
    id: 18,
    title: "Турнир по киберспорту",
    description: "Лучшие команды соревнуются в CS2, Valorant и LoL.",
    categories: ["Игры", "Технологии", "Киберспорт"],
    image: "/images/events/esports.jpg",
    location: "Киберарена, Москва",
    date: "2025-06-27T12:00:00",
  },
  {
    id: 19,
    title: "Ночь музеев",
    description: "Музеи открыты до утра! Экскурсии, квесты и арт-инсталляции.",
    categories: ["Культура", "Ночь музеев", "Искусство"],
    image: "/images/events/night-of-museums.jpg",
    location: "Музеи города, по всей России",
    date: "2025-05-18T20:00:00",
  },
  {
    id: 20,
    title: "Йога в парке",
    description: "Расслабляющая утренняя практика на свежем воздухе.",
    categories: ["Спорт", "Здоровье", "На свежем воздухе"],
    image: "/images/events/yoga.jpg",
    location: "Парк Победы, Москва",
    date: "2025-07-04T08:00:00",
  },
];
